"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    name='The JSONing',
    version='0.1.0',
    packages=['src'],
    author='mallocator',
    author_email='mallox@pyxzl.net',
    url='https://github.com/mallocator/JSONing',
    app=['src/main.py'],
    options={
        'py2app':{
            'argv_emulation': True,
            'site_packages': True
        }
    },
    setup_requires=['py2app'],
    license='Apache License 2.0',
)
